### ISSUE TITLE
Invalid UTF-32LE Byte Order Mark

### ISSUE THREAD

**Issue by bsia** [datacite/oaip#35]
https://github.com/datacite/oaip/blob/8f9c9ecb3dcc30c4822aefd0c989f9034b2cef90/src/main/java/datacite/oai/provider/util/BOMUtil.java#L35

The proper UTF-32LE BOM should be:  `0xFF, 0xFE, 0x00, 0x00`

**Comment by mfenner** [comment]
Documentation: http://unicode.org/faq/utf_bom.html.

**Comment by mfenner** [comment]
Thanks @bsia!
